package net.watsonplace.ecobee.api;

public class Alert {
	private String acknowledgeRef; // The unique alert identifier. This is required to acknowledge an alert.	
	private String date; // The alert date: YYYY-MM-DD
	private String time; // The alert time: HH:MM:SS
	private String severity; // The alert severity. Values: low, medium, high.
	private String text; // The alert message text. Will be truncated to 500 characters if longer.
	private Integer alertNumber; // The ecobee alert message identifier
	private String alertType; // The type of alert this is. Values: alert, demandResponse, emergency, message, pricing.
	private Boolean isOperatorAlert; // Whether the alert was generated by the thermostat owner
	private String reminder; // Whether a reminder will be sent.
	private Boolean showIdt; // Whether to show the alert on the thermostat.
	private Boolean showWeb; // Whether to show the alert on the ecobee web portal.
	private Boolean sendEmail; // Whether to send an alert email to the thermostat user.
	private String acknowledgement; // The user acknowledgement type. Values: accept, decline, defer, unacknowledged.
	private Boolean remindMeLater; // Whether to remind the user at a later time about the alert.
	private String thermostatIdentifier; // The identifier of the thermostat that generated the alert
	private String notificationType; // The type of Alert or reminder. Possible values are: alert, hvac, furnaceFilter, humidifierFilter, dehumidifierFilter, ventilator, ac, airFilter, airCleaner, uvLamp, temp, lowTemp, highTemp, lowHumidity, highHumidity, auxHeat, auxOutdoor. If the configuration for the specific alert type is required, see NotificationSettings
}
