package net.watsonplace.ecobee.api;

import java.lang.reflect.Type;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;

public class Alert extends APIObject {
	public static String[] APIObjectIdentifier = new String[] { "alert" };
	public static Type APIObjectType = new TypeToken<Alert>(){}.getType();
	
	String acknowledgeRef; // The unique alert identifier. This is required to acknowledge an alert.	
	String date; // The alert date: YYYY-MM-DD
	String time; // The alert time: HH:MM:SS
	String severity; // The alert severity. Values: low, medium, high.
	String text; // The alert message text. Will be truncated to 500 characters if longer.
	Integer alertNumber; // The ecobee alert message identifier
	String alertType; // The type of alert this is. Values: alert, demandResponse, emergency, message, pricing.
	Boolean isOperatorAlert; // Whether the alert was generated by the thermostat owner
	String reminder; // Whether a reminder will be sent.
	Boolean showIdt; // Whether to show the alert on the thermostat.
	Boolean showWeb; // Whether to show the alert on the ecobee web portal.
	Boolean sendEmail; // Whether to send an alert email to the thermostat user.
	String acknowledgement; // The user acknowledgement type. Values: accept, decline, defer, unacknowledged.
	Boolean remindMeLater; // Whether to remind the user at a later time about the alert.
	String thermostatIdentifier; // The identifier of the thermostat that generated the alert
	String notificationType; // The type of Alert or reminder. Possible values are: alert, hvac, furnaceFilter, humidifierFilter, dehumidifierFilter, ventilator, ac, airFilter, airCleaner, uvLamp, temp, lowTemp, highTemp, lowHumidity, highHumidity, auxHeat, auxOutdoor. If the configuration for the specific alert type is required, see NotificationSettings
	
	@Override
	public String[] getAPIObjectIdentifier() {
		return APIObjectIdentifier;
	}

	@Override
	public String toJson() {
		return super.toJson(APIObjectIdentifier[0]);
	}
	

}
